grub: add optional additional cmdline parameters
adfinis-sygroup/ansible-roles pull request #51
Opened 2018-03-01 13:51 UTC by keachi

Sometimes additional cmdline options are needed. This PR allows to add a free list of additional cmdline options.

2018-03-02 09:20 UTC, karras requested changes

2018-03-02 09:20 UTC, karras commented on grub/defaults/main.yml
> +# type: list
Would it make sense to add an example?

2018-03-05 09:05 UTC, keachi commented on grub/defaults/main.yml
> +# type: list
added an example :)

2018-03-05 19:22 UTC, karras approved these changes
LGTM

2018-03-05 19:23 UTC, merged